runtime: python27
api_version: 1
threadsafe: true
service: dashport-ui

handlers:

- url: /
  static_files: build/index.html
  upload: build/index.html
  secure: always
  redirect_http_response_code: 301

- url: /manifest.json
  static_files: build/manifest.json
  upload: build/manifest.json

- url: /asset-manifest.json
  static_files: build/asset-manifest.json
  upload: build/asset-manifest.json

- url: /favicon.ico
  static_files: build/favicon.ico
  upload: build/favicon.ico

- url: /static/(.*)
  static_files: build/static/\1
  upload: build/static/(.*)

- url: /assets/(.*)
  static_files: build/assets/\1
  upload: build/assets/(.*)

- url: /(.*)
  static_files: build/index.html
  upload: build/index.html
  secure: always
  redirect_http_response_code: 301


skip_files:
  - node_modules/
  - .git/
